baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shrutisolanki.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-webp
  - jekyll_picture_tag

compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Install cwebp-bin using npm
# npm install --global cwebp-bin
# webp:
#   enabled: true
#   quality: 75
#   img_dir: ["/assets/images/portfolio/handmade", "/assets/images/portfolio/digital", "/assets/images/portfolio/accessories"]
#   nested: false
#   # add ".gif" to the format list to generate webp for animated gifs as well
#   formats: [".jpeg", ".jpg", ".png", ".tiff"]
#   # File extensions for animated gif files 
#   gifs: [".gif"]
#   # Set to true to always regenerate existing webp files
#   regenerate: false
#   # List of files or directories to exclude
#   exclude: []
#   # append '.webp' to filename after original extension rather than replacing it.
#   # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
#   append_ext: true
#   webp_path: /usr/local/bin/cwebp

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
