#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: Handmade Accessories,
      icon: ti-palette,
      description: "Update icon and description",
      active: , # Add true to select section
    }
  - {
      name: Digital Artwork,
      icon: ti-vector,
      description: "Update icon and description",
      active: true, # Add true to select section
    }
  - {
      name: Custom Artwork,
      icon: ti-panel,
      description: "Update icon and description",
      active: ,# Add true to select section
    }