---
#-------------------------------
# General Site Settings

title: Pocassinator
# logo:
author: Shruti Solanki
description: I am Po!
email: hi@shrutisolanki.com
# phone: 
address: New Delhi, India
copyright: Copyright &copy; 2023

menu:
  - { name: About, link: "/about" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Blog, link: "/blog" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: steve.fruits@email.com
